const breedInfoData = [
  {
    name: `akita`,
    id: `akita`,
    cardDesc: `A breed of hunting dog from Japan.`,
    cardImg: "https://images.dog.ceo/breeds/akita/An_Akita_Inu_resting.jpg",
    headImg:
      "https://cdn.britannica.com/59/234759-050-DA4F2DCF/Akita-dog-Japan.jpg",
    subDesc: `Also known as: Akita Inu, Japanese Akita`,
    desc: `This is a large and powerful breed, with much substance and heavy bone, and is slightly longer than tall. The Akita’s build reflects its original job of finding big game in deep snow and rugged terrain. This breed’s double coat consists of a dense undercoat and straight, rough, outer coat standing off from the body, about 2 inches or less in length. Such a combination provides ample insulation from water and weather. The gait is brisk and powerful. The Akita is a versatile dog of large spitz type, able to perform as hiking companion and protector.`,
    history: `The Akita is perhaps the most renowned and venerated of the native Japanese breeds. Although it bears a likeness to dogs from ancient Japanese tombs, the modern Akita is the result of a concerted nineteenth century effort to restore seven native Japanese dog breeds. The Akita, largest of these breeds, was restored using many breeds, including indigenous Odate dogs, which were used as the best representatives of native Japanese animals. Over time, Japanese breeders selected against many traits descended from some ancestors, including black mask, pinto pattern, and substantial size; whereas American breeders perpetuated those traits. In 1918, the Akita-inu Hozankai Society of Japan was formed to preserve the original Akita, and in 1931 the Akita was designated as one of Japan’s natural monuments. The most honored Akita of all time was Hachiko, who greeted his master every evening at the train station to accompany him home. When his master died at work one day, Haichiko waited for him, and continued to return and wait for his master every day until he died nine years later on March 8, 1935. Today, a statue and annual ceremony pay homage to Haichiko’s loyalty. The first Akita arrived in America in 1937, when Helen Keller returned from Japan with one. Following World War II, servicemen returned home with Akitas from Japan. The breed’s popularity grew slowly until it received AKC recognition in 1972. Since then, it has steadily gained admirers and continues to grow in popularity. The Akita is now used as a guard and police dog in Japan.`,
    temperament: `As befitting its spitz-like heritage, the Akita is bold, independent, stubborn, and tenacious. Demonstrative to their family, they are utterly devoted and will protect family members. This dog is reserved with strangers and can be assertive, so should be introduced carefully to new dogs and household pets. They can be domineering. Though not the breed for everyone, in the right hands the Akita is an excellent companion.`,
    upkeep: `The Akita appreciates mental and physical exercise every day. They need the chance to run in a safe area or on leash for a long jog. Given ample exercise and training, this dog can be a quiet and well-mannered house dog. The coat needs brushing about once a week to remove dead hair, much more often when shedding. Akitas tend to be somewhat messy drinkers!`,
    health: [
      `Major concerns: CHD, PRA`,
      `Minor concerns: elbow dysplasia, pemphigus, sebaceous adenitis, gastric torsion, cruciate ligament rupture, osteosarcoma, lymphosarcoma, hypothyroidism`,
      `Occasionally seen: PRA, patellar luxation, VKH-like syndrome, entropion, epilepsy, cataract, polyneuropathy, renal cortical hypoplasia, microphthalmia`,
      `Suggested tests: hip, (elbow), eye, thyroid`,
      `Life span: 10–12 years`,
      `Note: Akitas are especially sensitive to anemia from red blood cell damage caused by eating onions.`,
    ],
    size: 5,
    energyLvl: 3,
    exReqs: 3,
    playfulness: 3,
    affLvl: 3,
    frToDogs: 1,
    frToPets: 2,
    frToStr: 1,
    watchfulness: 4,
    easeTr: 3,
    groomReqs: 2,
    heatSens: 5,
    vocality: 5,
  },
  {
    name: `pitbull`,
    id: `pitbull`,
    cardDesc: `An american family dog breed.`,
    cardImg:
      "https://images.dog.ceo/breeds/pitbull/IMG_20190826_121528_876.jpg",
    headImg: "https://wallpaperaccess.com/full/1814445.jpg",
    subDesc: `Also known as: American Pit Bull Terrier`,
    desc: `Few dog breeds have the ability to cause strong reactions in a room like the “Pit Bull.” Whether (like many animal-care workers) you’ve known and loved dogs with this label – or you have a fear of dogs with blocky heads and strong bodies who have been depicted in a negative light by the media, the term Pit Bull can often spark both positive and negative emotions here in the U.S. Even so, people are often surprised when they learn that “Pit Bull” is not an actual breed of dog. Instead, the term is used to describe a collection of a few different bully breeds, and many dogs get classified as “Pit Bull” even when they don’t belong to one of the breeds most commonly associated with the term. Since the term “Pit Bull” is ambiguous and flexible, it may be more accurate to say, “pit bull-type dogs,” and there has been a recent movement in animal welfare to remove the breed label entirely.`,
    history: `The first Pit Bulls originated in England. They were bred from Old English Bulldogs, and were used in the early 1800s as fighting dogs in a sport known as bull baiting. Later in 1835, when this was outlawed in England, dog fighting and rat baiting gained popularity. Bulldogs were then crossed with Terriers to create smaller and more agile fighting dogs. These dogs closely resembled the Pit Bulls we know today.
    Despite originally being bred as fighting dogs, Pit Bull-type dogs gained a reputation for being friendly to humans and being loyal companions. The first immigrants to America brought their dogs with them, and many took on roles such as herding dogs, hunting dogs, and guard dogs. These intelligent, vibrant and gentle dogs also made excellent family companions. The look of Pit Bull-type dogs grew in notoriety, and they were so beloved they were even used in WWI and WWII in advertising as a national mascot.
    In fact, many famous Pit Bulls have gained national love, including Sergeant Stubby who served in WWI and performed heroic acts of bravery, and Petey from the TV show The Little Rascals. However, a shift occurred in the 1970s and 80s, perhaps spurred by a resurgence in illegal dog fighting. National media began to sensationalize these dogs, and they’ve become a common target of breed specific legislation. Over-breeding, their vivacious personalities and this stigma have resulted in dogs labelled Pit Bull being those most-often found in U.S. shelters today.
    Thankfully, Pit Bull enthusiasts have made recent progress in showing these clown-like and sweet-natured dogs for the individuals they are, and the tide of breed-specific legislation has been receding.`,
    temperament: `Pit Bulls are typically affectionate, loyal, playful, and eager to please. They are also generally very good with children, although their boisterous nature can make them a bit over-exuberant for some small children. Despite this, the public perception of Pit Bulls is often quite the opposite. The negative stigma surrounding them stems in part from the fact that they are often associated with dog fighting and serving as guard dogs for criminal gangs. The mainstream media also tends to over-report Pit Bull attacks on humans.
    It’s important to make sure that you check with local laws and housing if you’re considering adding a Pit Bull to your home. Breed-specific legislation often targets these dogs and many insurance providers or housing associations have different rules about them. Because of the negative stigma surrounding Pit Bulls, people who choose to share their lives with these wonderful dogs should also be aware that they’ll have to be their advocates.`,
    upkeep: `Pit Bulls are athletic and energetic dogs that require frequent exercise. Stick to a daily walking routine and provide plenty of mental and physical stimulation both inside and outside the home. Socialization and positive reinforcement training can be very effective for preventing destructive behaviors.
    When it comes to coat care, Pit Bulls are relatively low maintenance. Brushing their short coat weekly will remove dead fur and keep them looking their best. Most Pit Bulls will need bathing no more than once a month.`,
    health: [
      `Major concerns: CHD, PRA`,
      `Minor concerns: thyroid disorders, hip dysplasia`,
      `Occasionally seen: cataracts, allergies`,
      `Suggested tests: hip, cardiac, thyroid, eye`,
      `Lifespan: 10-15 years`,
      `Note: CHD seldom causes problems or symptoms`,
    ],
    size: 5,
    energyLvl: 3,
    exReqs: 3,
    playfulness: 4,
    affLvl: 4,
    frToDogs: 2,
    frToPets: 2,
    frToStr: 3,
    watchfulness: 5,
    easeTr: 4,
    groomReqs: 1,
    heatSens: 2,
    vocality: 4,
  },
  {
    name: `husky`,
    id: `husky`,
    cardDesc: `A working sled dog breed.`,
    cardImg:
      "https://i.pinimg.com/564x/9b/42/6b/9b426ba008b280c0da576dba061bc582.jpg",
    headImg:
      "https://highlandcanine.com/wp-content/uploads/2021/01/siberian-husky-in-the-snow.jpg",
    subDesc: ``,
    desc: `The Siberian Husky combines power, speed, and endurance. They are moderately compact, slightly longer than they are tall, and of definite Northern heritage. They are quick and light on their feet, with a smooth and effortless stride exhibiting both good reach and drive. They have a double coat of medium length, with a soft, dense undercoat and straight, somewhat flat-lying outer coat. Their expression is often keen but friendly, interested, and sometimes even mischievous.`,
    history: `The Chukchi people of northeast Asia developed the breed now known as the Siberian Husky. Their ancestry is unknown, but they are of obvious spitz origins, evolved over hundreds of years as a sledge dog for these nomadic people. During the Alaskan gold rush, dogs became a vital part of life in the Arctic regions.
    In 1909 the first Chukchi huskies were brought to North America from Siberia for The All-Alaska sweepstakes race. Smaller and more docile than most of the other competitors in the race, they aroused little admiration, with the exception of one racer who was so impressed he imported seventy to train for the 1910 race. Throughout the rest of the year, the dogs earned their keep as utilitarian sledders, but it was in 1925 that they gained their greatest acclaim. Teams of Huskies raced 340 miles with life-saving serum for diphtheria stricken Nome, AK and were credited with saving the town. A statue in their honor stands in Central Park.
    The first Siberian Huskies came to Canada, and then the rest of the United States, at around this time. The AKC recognized the breed in 1930. During World War II, many Siberians served in the U.S. Army’s Search and Rescue teams, further capturing the public’s admiration. The breed’s popularity continued to grow and now this breed is cherished family pet. They remain one of the most popular of the Arctic breeds.`,
    temperament: `Fun-loving, adventurous, alert, independent, clever, stubborn, mischievous, and obstinate all describe the Siberian Husky. This breed loves to run and will roam if given the chance. They may be very assertive toward strange dogs, but they are generally good with other dogs in the home. In fact, they are very social and must have lots of human or canine companionship. They may chase strange cats or small pets. Some are likely to howl, dig, and chew.`,
    upkeep: `This is a very active dog. They need ample daily exercise, either in the form of a long jog, hike or a long run off-leash in a safe and enclosed area. They also love to pull and tend to enjoy cold weather. Their coat needs brushing one or two times a week, daily during periods of heaviest shedding.`,
    health: [
      `Major concerns: none`,
      `Minor concerns: PRA, cataract, corneal dystrophy, hypothyroidism`,
      `Occasionally seen: CHD`,
      `Suggested tests: eye, (thyroid), hip`,
      `Life span: 11–13 years`,
    ],
    size: 5,
    energyLvl: 3,
    exReqs: 4,
    playfulness: 4,
    affLvl: 4,
    frToDogs: 3,
    frToPets: 3,
    frToStr: 5,
    watchfulness: 1,
    easeTr: 1,
    groomReqs: 4,
    heatSens: 5,
    vocality: 3,
  },
  {
    name: `samoyed`,
    id: `samoyed`,
    cardDesc: `A breed of medium-sized herding dogs.`,
    cardImg:
      "https://i.pinimg.com/1200x/12/c6/f0/12c6f07612826a4ecaa52d7fb825b5b3.jpg",
    headImg:
      "https://i.pinimg.com/564x/fc/67/37/fc673783b1e494f0beb83a15f8d63950.jpg",
    subDesc: `Also known as Samoyedskaya`,
    desc: `The Samoyed combines strength, agility, dignity, and grace in a general spitz outline. Slightly longer than they are tall, they are nonetheless compact. They have a strong, muscular body that is able to combine power, speed, agility, and endurance. They have a quick, agile stride with good reach and drive. Their double coat is heavy and weather resistant. Their undercoat is soft and thick, whereas the outer coat is straight and harsh, standing straight out from their body, and glistening with a silver sheen. Their expression is often animated, with the characteristic “Samoyed smile” created by the upcurved corners of their mouth.`,
    history: `The nomadic Samoyed people, for whom the Samoyed dog is named, came to northwestern Siberia from central Asia. They depended upon herds of reindeer for food, and had to keep on the move in order that the reindeer could find sufficient food for themselves. They also depended upon strong hardy spitz dogs to herd the reindeer and to guard them against the fierce predators of the Arctic. They occasionally helped to hunt and tow boats and sledges. These dogs lived as part of the family in the hide tents of their families, where one of their “jobs” was to keep the children warm in bed.
    The first Samoyeds came to England in the late 1800s, but not all these early imports were the pure white the breed is known for today. One of these dogs was presented to Queen Alexandria, who did much to promote the breed. Descendants of the queen’s dogs can still be found in modern pedigrees.
    In 1906, the first Samoyed came to America, originally a gift of Russia’s Grand Duke Nicholas. In the early 1900s, Samoyeds formed part of the sled teams on the expeditions to Antarctica and shared in the triumph of reaching the South Pole. The breed’s exploits, combined with their glistening good looks, soon won the public’s attention in America, and their popularity has grown tremendously since the Second World War. Although the once nomadic Samoyed people have long since settled in one place, the breed they created has journeyed around the world.`,
    temperament: `Gentle and playful, the Samoyed often makes a good companion for a child or person of any age. They are a closely bonded family dog. They are generally amiable with strangers, other pets, and usually, other dogs. They can be calm indoors, but this clever, sometimes mischievous breed needs daily physical and mental exercise. If allowed to become bored, they will dig and bark. They are independent and often stubborn, but they are willing to please and responsive to their family.  They may tend to herd children.`,
    upkeep: `The Samoyed is active and needs a good workout every day, either in the form of a long walk or jog or a vigorous play session. They often like to pull and herd, and they prefer cooler weather. Their thick coat needs brushing and combing two to three times a week, daily when shedding.`,
    health: [
      `Major concerns: CHD`,
      `Minor concerns: gastric torsion, cataract, hypothyroidism`,
      `Occasionally seen: PRA, diabetes, RD/OSD, PDA`,
      `Suggested tests: hip, eye, DNA for PRA, DNA for RD/OSD, cardiac`,
      `Life span: 10–12 years`,
    ],
    size: 5,
    energyLvl: 3,
    exReqs: 3,
    playfulness: 4,
    affLvl: 4,
    frToDogs: 3,
    frToPets: 5,
    frToStr: 4,
    watchfulness: 1,
    easeTr: 2,
    groomReqs: 5,
    heatSens: 5,
    vocality: 5,
  },
  {
    name: `beagle`,
    id: `beagle`,
    cardDesc: `A small scent hound.`,
    cardImg:
      "https://i.pinimg.com/originals/d5/a1/60/d5a160bedebc3d9b0c5b63c105198232.jpg",
    headImg:
      "https://www.purina.com.au/-/media/project/purina/main/breeds/dog/dog_beagle_desktop.jpg",
    subDesc: `(English Beagle)`,
    desc: `The Beagle should look like a miniature Foxhound, and is solid for the size. The Beagle’s moderate size enables the ability to follow on foot. Beagles can also be carried, and they can scurry around in thick underbrush. Their close hard coat protects them from underbrush. Their moderate build enables them to nimbly traverse rough terrain. The Beagle’s amiable personality allows this breed to get along with other dogs and to be a wonderful pet. Beagles are noted for their melodious bay. The deep muzzle allows more room for olfactory receptors, aiding the Beagle’s uncanny sense of smell.`,
    history: `By the fourteenth century, hare-hunting had become a popular sport in England, and the dogs used were probably of Beagle type. The origin of the name Beagle may be from old French words meaning open throat in reference to the breed’s melodious bay, or from the Celtic, old English, or old French words for small. The word Beagle was not used until 1475, however, but can then be found frequently in writings from the sixteenth century on.
      Hunters could follow these dogs on foot and could even carry one in a pocket if the need arose. By the 1800s, Beagles existed in several sizes, but the smaller “pocket-size” dogs were particularly popular. These dogs measured only about 9 inches and often needed the hunter’s assistance in crossing rough fields. One of the special appeals of the smaller Beagles was that the hunt could be followed even by “ladies, the aged, or the infirm,” as they slowly followed the winding path of the hare.
      The first mention of the Beagle in America was in 1642. Beagles were used in the South prior to the Civil War, but these dogs bore little resemblance to their English counterparts. After the war, English imports formed the basis of the modern American Beagle. By the end of the nineteenth century, Beagles were popular competitors in both field and conformation exhibitions. But the merry little scenthound did not stop there: the Beagle continued to become one of America’s all-time favorite breeds, finding a special niche as family pet.`,
    temperament: `One of the most amiable hounds, the Beagle was originally bred to be part of a pack and needs companionship, whether human or canine. This dog loves to explore the outdoors and is an enthusiastic trailer. Given adequate exercise, the Beagle is a calm, tractable house pet. Beagles tend to be excellent with children, gentle, incredibly tolerant, and always ready to join in a game or adventure. This is an independent breed, however, and may run off if a trail beckons. Beagles bark and howl.`,
    upkeep: `The Beagle needs daily exercise, either a long walk on leash or a romp in a safe area. Coat care requires only occasional brushing and bathing.`,
    health: [
      `Major concerns:  intervertebral disk disease, CHD`,
      `Minor concerns: glaucoma, epilepsy, CPRA, hypothyroidism, patellar luxation, chondrodysplasia, cherry eye, distichiasis, KCS`,
      `Occasionally seen: deafness, hemophilia A, cataract, demodicosis, umbilical hernia, Musladin-Leuke Syndrome (MLS)`,
      `Suggested tests: hip, eye, (thyroid), DNA for MLS`,
      `Life span: 12–15 years`,
    ],
    size: 3,
    energyLvl: 3,
    exReqs: 3,
    playfulness: 4,
    affLvl: 5,
    frToDogs: 5,
    frToPets: 5,
    frToStr: 5,
    watchfulness: 1,
    easeTr: 1,
    groomReqs: 1,
    heatSens: 3,
    vocality: 4,
  },
  {
    name: `boxer`,
    id: `boxer`,
    cardDesc: `A German dog breed of mastiff-type.`,
    cardImg:
      "https://i.pinimg.com/564x/90/87/de/9087de58fffc3a0e86f664448858d963.jpg",
    headImg:
      "https://www.scotsman.com/webimg/b25lY21zOjM1NTM5YWE3LTlmMmMtNDc0Yi1iM2U3LTJjMmJkMTI0YzgzMzoyYjM1ODY1NC1jYTg4LTQxYTEtYjhlNy1kOTEyM2RlNTY5ZWM=.jpg",
    subDesc: ``,
    desc: `The Boxer is exemplary in the combination of stylish elegance with strength and agility. This breed is square-proportioned with good substance and musculature. The Boxer’s stride is free and ground covering, with proud carriage. The head is distinctive, with a broad, blunt muzzle and alert expression. The coat is short and shiny. This dog is perfectly suited to serve as a working watchdog.`,
    history: `The Boxer derives from two central European breeds of dog that no longer exist: the larger Danziger Bullenbeiser and smaller Brabenter Bullenbeiser. Bullenbeiser means bull-biter, and these dogs were used to chase large game through the forest. This required a strong but agile dog with a broad powerful jaw and a recessed nose. In England, the Bulldog was the favored breed for the sport, whereas in Germany large mastiff-type dogs were used.
      Around the 1830s, German hunters began a concerted effort to create a new breed, crossing their Bullenbeisers with mastiff-type dogs for size, terriers for tenacity, and, finally, Bulldogs. The result was a tough agile dog with a streamlined body and strong grip. By 1895, an entirely new breed, the Boxer, had been established. Although the exact origin of the name Boxer is obscure, it may have been derived from the German Boxl. The Boxer was one of the first breeds to be employed as a police and military dog in Germany.
      By 1900, the breed had become established as a general utility dog, family pet, and even show dog. The AKC recognized the breed soon after, but only in the 1940s did the breed begin its steady rise to the top of the popularity charts, eventually peaking as the fourth most popular breed in America.`,
    temperament: `The Boxer is playful, exuberant, inquisitive, attentive, demonstrative, devoted, and outgoing; this dog is a perfect companion for an active family. Boxers can be stubborn, but are sensitive and responsive to commands. They may be assertive toward strange dogs, but are generally good with other family dogs and pets.`,
    upkeep: `The Boxer needs daily mental and physical exertion. They likes to run, but their exercise needs can also be met with a good jog or long walk on leash. They do not do well in hot weather. Some snore. The coat needs only occasional brushing to remove dead hair.`,
    health: [
      `Major concerns:  boxer cardiomyopathy, SAS, CHD`,
      `Minor concerns: gastric torsion, hypothyroidism, corneal erosion, colitis`,
      `Occasionally seen: brain tumors, degenerative myelopathy`,
      `Suggested tests: thyroid, hip, cardiac (Holter monitoring)`,
      `Life span: 8–10 years`,
      `Note: Sensitive to heat.White boxers may be deaf.The drug acepromazine can cause severe reactions.`,
    ],
    size: 3,
    energyLvl: 5,
    exReqs: 3,
    playfulness: 5,
    affLvl: 5,
    frToDogs: 3,
    frToPets: 3,
    frToStr: 3,
    watchfulness: 5,
    easeTr: 3,
    groomReqs: 1,
    heatSens: 5,
    vocality: 3,
  },
  {
    name: `dane`,
    id: `dane`,
    cardDesc: `A large sized dog breed originating from Germany.`,
    cardImg:
      "https://i.pinimg.com/564x/4b/20/53/4b205301d6f2a68cf544571e7c940b5f.jpg",
    headImg:
      "https://www.scotsman.com/webimg/b25lY21zOjZlZTMwMGRkLWNiZDItNGVkMy05YTEzLTNiNTQ3NDYyMjQ1ZDo0MDZiNTU0ZC1kMDI1LTQ1ZGUtYjFjMi03MDliYmUyOTZiNzA=.jpg",
    subDesc: `(Deutsche Dogge, German Mastiff)`,
    desc: `This regal breed combines great size and power with elegance. They are square proportioned and well balanced. The gait is strong and powerful with long, easy strides. The coat is short, thick, and glossy. The Great Dane is most noteworthy for its majestic carriage and appearance— the Apollo of Dogs.`,
    history: `Dubbed the “Apollo of Dogs,” the Great Dane is probably the product of the ancient Molossus war dog and the Greyhound. With these ancestors, its ability as a fearless big game hunter seemed only natural. By the fourteenth century, these dogs were proving themselves as able hunters in Germany, combining speed, stamina, strength, and courage in order to bring down the tough wild boar. The dogs became popular with the landed gentry not only because of their hunting ability but also because of their imposing yet graceful appearance.
      These noble dogs made gracious additions to any estate. British familiar with the breed first referred to them as German Boarhounds. Exactly when and why the breed was later dubbed the Great Dane is a mystery because, although undeniably great, it is not Danish. It is a German breed, and in 1876, the breed was declared Germany’s National Dog. In 1880 German authorities declared the dog should be called the Deutsche Dogge, the name by which it still goes in Germany. The English paid no heed, and the old name stuck for the English-speaking world. By the late 1800s, the Great Dane had come to America. It quickly attracted attention, as it does to this very day. The breed has since achieved great popularity in spite of some of the challenges owning a giant dog entails. The record of world’s tallest dog has been held by several Great Danes.`,
    temperament: `The Great Dane is spirited, courageous, friendly, and dependable. He is generally good with children (although his friendly overtures may overwhelm a small child) and usually friendly toward other household dogs and pets, but like all large dogs should be supervised. With training, he makes a pleasant, well-mannered family companion.`,
    upkeep: `The Great Dane needs daily moderate exercise. His needs can be met with a good walk or romp. He needs soft bedding and sufficient room to stretch out when sleeping. Some tend to drool. Coat care is minimal.`,
    health: [
      `Major concerns: gastric torsion, cardiomyopathy, osteosarcoma`,
      `Minor concerns: CHD, CVI (Wobbler’s syndrome), OCD, HOD, hypothyroidism`,
      `Occasionally seen: vWD, cataract, entropion`,
      `Suggested tests: cardiac, hip, eye, thyroid, cardiac`,
      `Life span: 7–10 years`,
      `Note: Danes are usually bred within three separate color families: fawn and brindle; harlequin and mantle; and black and blue. Because dogs from the color families are seldom interbred, each color family tends to have different characteristics and health concerns.`,
    ],
    size: 5,
    energyLvl: 2,
    exReqs: 2,
    playfulness: 2,
    affLvl: 4,
    frToDogs: 2,
    frToPets: 2,
    frToStr: 4,
    watchfulness: 3,
    easeTr: 3,
    groomReqs: 1,
    heatSens: 4,
    vocality: 4,
  },
  {
    name: `chihuahua`,
    id: `chihuahua`,
    cardDesc: `A breed of toy dog.`,
    cardImg:
      "https://img.freepik.com/premium-photo/cute-chihuahua-dog-home_251840-1181.jpg",
    headImg:
      "https://img.freepik.com/premium-photo/chihuahua-puppy-little-dog-garden-cute-small-doggy-grass-short-haired-chihuahua-breed_77829-4974.jpg",
    subDesc: ``,
    desc: `The Chihuahua is graceful, small, and compact, slightly longer than he is tall. The Chihuahua has a saucy expression and alert, terrier-like attitude. The coat can be smooth, with soft, glossy hair, or long, with soft straight or wavy coats and fringed ears.`,
    history: `The smallest breed of dog, the Chihuahua has a controversial history. One theory holds that it originated in China and was brought to the New World by Spanish traders, where it was then crossed with small native dogs. The other theory contends that it originated entirely in Central and South America, descending from the native Techichi. A small red dog was believed to guide the soul to the underworld, and every Aztec family kept such a dog that was buried with any deceased family member. To make matters worse for the Techichi, the Toltecs and their conquerors, the Aztecs, often ate dogs and the Techichi may have sometimes been on the menu. Despite what may have been short lives, the Techichis apparently were well cared for during life by the priests or their families. In fact, the most likely origin of the Chihuahua is a combination of these theories: the native Techichi was probably crossed with tiny hairless Chinese dogs, but again the date when this occurred is controversial.
      The Chinese dogs may have been brought over when a land bridge spanned the Bering Strait, or they may have been brought later by Spanish traders. When Cortes conquered the Aztecs in the sixteenth century, the little dogs were abandoned and left to fend for themselves. About 300 years later, in 1850, three tiny dogs were found in Chihuahua, Mexico. A few were brought to the United States, but they aroused only moderate attention. Only when Xavier Cugat (“the rhumba king”) appeared in public with a Chihuahua as his constant companion did the breed capture the public’s hearts. It experienced a meteoric rise in popularity and has continued as one of America’s most popular breeds.`,
    temperament: `The saucy Chihuahua has earned his place as a favored toy dog because of his intense devotion to a single person. He is reserved with strangers but good with other household dogs and pets. Some try to be protective, but they are not very effective. Some may be quite bold; others may be timid. He may often  be temperamental. Some bark.`,
    upkeep: `The Chihuahua is a lively dog that nonetheless can get his exercise running from room to room indoors. He enjoys exploring the yard or going for a short walk on leash and especially enjoys accompanying his owner on outings. He hates the cold and seeks out warmth. Coat care for the smooth is minimal. Care of the long coat entails brushing two to three times a week.`,
    health: [
      `Major concerns: none`,
      `Minor concerns: pulmonic stenosis, hydrocephalus, patellar luxation, KCS, hypoglycemia`,
      `Occasionally seen: none`,
      `Suggested tests: cardiac, knee, eye`,
      `Life span: 14–18 years`,
      `Note: A soft spot (molera) in the skull (due to incomplete fontanel closure) is a common breed trait.`,
    ],
    size: 1,
    energyLvl: 5,
    exReqs: 1,
    playfulness: 2,
    affLvl: 2,
    frToDogs: 1,
    frToPets: 3,
    frToStr: 1,
    watchfulness: 1,
    easeTr: 2,
    groomReqs: 2,
    heatSens: 2,
    vocality: 5,
  },
  {
    name: `dalmatian`,
    id: `dalmatian`,
    cardDesc: `A breed of medium-sized dog, noted for its unique coat.`,
    cardImg:
      "https://i.pinimg.com/564x/fc/61/ab/fc61ab683b3b33b346e03b20208e62cf.jpg",
    headImg: "https://wallpapercave.com/wp/wp3910468.jpg",
    subDesc: ``,
    desc: `The Dalmatian is a square-proportioned, athletic dog of good substance and sturdy bone. They are built for efficiency at the trot and great endurance, and their movement should be steady and effortless. The expression is alert and intelligent; the coat short and sleek.`,
    history: `The spotted Dalmatian is the most distinctly patterned breed of any dog, but the origin of its coat pattern is unknown. In fact, although art evidence points to an ancient origin, the time and place of the breed’s birth is also unknown. It gets it name from Dalmatia, a region in western Yugoslavia, but it probably did not originate there. Their ancestors may have included a small version of the spotted Great Dane or pointers, though this, too, is conjectural. Even the breed’s original function is unclear, but that is more likely because of its use in so many roles rather than any lack of employment. These roles included war dog, sentinel, shepherd, draft dog, retriever, trailer, and even circus dog.
      It was as a coach dog in Victorian England, however, that the Dalmatian found its niche. The coach dog served both a practical and anesthetic role; it protected the horses from marauding dogs and added a touch of style to the procession. The dogs would trot alongside, in front, or beneath the axle (considered the most elegant position) of the coach; interestingly, some evidence exists that coaching position may have a hereditary component.
      With the advent of the automobile, the Dalmatian lost their place in high society, and their popularity declined. They continued as a coach dog for horse-drawn fire engines, and this association led to their adoption as the modern “fire-dog.” The Dal was AKC recognized in 1888. Their flashy coloration has always ensured that it has been popular as a pet and show dog; however, it has had extreme ups and downs in popularity. Impulse buying followed movies featuring Dalmatian stars, followed by a backlash when so many of these unprepared homes were ill suited for Dalmatian ownership and laid the blame on the breed.`,
    temperament: `Bred to run for miles, the Dalmatian retains this tireless enthusiasm. He is a playful, eager companion that must get daily hard exercise in a safe area if it is expected to behave at home. He loves to run and may roam. He may be assertive toward strange dogs, but he is generally good with other pets and is especially good with horses. He may be too energetic for young children. He tends to be reserved toward strangers. He can be stubborn. Note: Deaf Dalmatians present special training and behavioral challenges.`,
    upkeep: `The Dalmatian needs a lot of regular exercise and attention. He needs more than a short walk on leash; he makes a good jogging companion. He can also have his needs met with vigorous games and runs. The coat needs only occasional brushing.`,
    health: [
      `Major concerns: deafness, urinary stones`,
      `Minor concerns: allergies, seizures, iris sphincter dysplasia, hypothyroidism`,
      `Occasionally seen: CHD`,
      `Suggested tests: hearing, hip`,
      `Life span: 12–14 years`,
      `Note: A unique defect of the Dalmatian is its inability to metabolize uric acid into allantoin, which leads to the tendency to form urinary calculi (stones).`,
    ],
    size: 4,
    energyLvl: 4,
    exReqs: 3,
    playfulness: 3,
    affLvl: 5,
    frToDogs: 3,
    frToPets: 3,
    frToStr: 3,
    watchfulness: 3,
    easeTr: 3,
    groomReqs: 2,
    heatSens: 3,
    vocality: 4,
  },
  {
    name: `chow chow`,
    id: `chow`,
    cardDesc: `A spitz-type of dog breed from northern China.`,
    cardImg:
      "https://i.pinimg.com/564x/1c/a2/b3/1ca2b36a5e739f7ff9bf3ac718b51b16.jpg",
    headImg: "https://images.unsplash.com/photo-1569263321605-c70cb08d1d68",
    subDesc: ``,
    desc: `The Chow Chow is an Arctic-type dog, powerful, squarely built, and sturdy with heavy bone and strong muscular development. They were bred for a number of tasks, and and their build reflects their ability to herd, pull, and protect. They can have either a rough coat, which is straight and offstanding or a smooth coat, which is hard and smooth; both coat types have wooly undercoats, providing ample insulation from the cold. The characteristic straight angulation of the hind legs produces a short, stilted gait unique to the breed. The scowling expression and black tongue are essential components of breed type.`,
    history: `The Chow Chow has some spitz characteristics. Because of this, it has been proposed that the Chow Chow either descends from spitz forebears or is itself an ancestor of some of the spitz breeds. Unfortunately, the origin of the breed has been lost in time, but it has been known in China for hundreds, if not thousands, of years.
      Its original purpose may have been as a hunting dog, sniffing out and even pointing birds for the nobility. The breed declined in quality and numbers after the Imperial hunts were ended, but a few pure descendants were kept in isolated monasteries and wealthy households. One of the most distinctive features of the breed is its black tongue, which was also the basis for its more common names in China.
      Only when dogs were brought to England along with other Chinese importations in the late 1700s was the name Chow Chow adopted. The name is probably derived from a term simply meaning Oriental knick knack and assorted curios, and may have come to be applied to the dogs because they were lumped into a ship’s log of cargo. These early imports were, in fact, looked upon as curios. Not until the late 1800s was the breed imported to England and then America in earnest. Queen Victoria’s interest in these dogs helped draw attention to the breed. AKC recognized the Chow Chow in 1903. The breed’s distinctive noble look has always attracted fanciers, but in the 1980s the breed soared in popularity, peaking as the sixth most popular breed in America.`,
    temperament: `Dignified, even lordly, the Chow Chow conducts himself with reserve. He is not very demonstrative, even with his family, and he is somewhat suspicious of strangers. He can be independent and stubborn. He can be assertive toward other dogs but is generally good with other household pets. He may be serious and protective, devoted to his family.`,
    upkeep: `This is an alert breed that needs regular, but not strenuous, outdoor activity. He does not do well in hot humid weather. His needs are best met with casual morning or evening walks in warm weather or several short play sessions throughout the day. The smooth type needs brushing once weekly; the rough type needs brushing every other day, and daily when shedding.`,
    health: [
      `Major concerns: CHD, entropion, patellar luxation`,
      `Minor concerns: elbow dysplasia, cataract, distichiasis, PPM, gastric torsion, stenotic nares, glaucoma, elongated palate`,
      `Occasionally seen: renal cortical hypoplasia`,
      `Suggested tests: hip, elbow, eye, knee, thyroid`,
      `Life span: 8–12 years`,
    ],
    size: 3,
    energyLvl: 1,
    exReqs: 2,
    playfulness: 1,
    affLvl: 2,
    frToDogs: 1,
    frToPets: 3,
    frToStr: 1,
    watchfulness: 4,
    easeTr: 1,
    groomReqs: 4,
    heatSens: 5,
    vocality: 5,
  },
  {
    name: `german shepherd`,
    id: `germanshepherd`,
    cardDesc: `A German breed of working dog.`,
    cardImg:
      "https://i.pinimg.com/564x/38/53/e0/3853e07d931a48b0e12c97b86d509086.jpg",
    headImg: "https://wallpaper.dog/large/17098165.jpg",
    subDesc: ``,
    desc: `The German Shepherd Dog has an outline of smooth curves on a longer than tall body that’s strong, agile, substantial, and an exceptionally outreaching and elastic gait, covering the ground in great strides. The breed’s dense, straight or slightly wavy double coat comprises harsh, close lying medium length hair.`,
    history: `Perhaps never in the history of any breed has such concerted effort been put into improving a dog, mostly due to the formation in 1899 of the Verein fur Deutsche Scharferhunde SV, an organization in Germany devoted to overseeing the breeding of the German Shepherd.
      Breeders sought to develop not only a herding dog but also one that could excel at jobs requiring courage, athleticism, and intelligence.
      During World War I, they were the obvious choice for a war sentry. At the same time, the AKC changed the breed’s name from German Sheepdog to Shepherd Dog, and Britain changed it to Alsatian Wolfdog, both attempts to dissociate the dog from its unpopular German roots.
      The Wolfdog was later dropped as it caused many people to fear the dogs. In 1931, the AKC restored the breed’s name to German Shepherd Dog.`,
    temperament: `Among the most intelligent of breeds, the German Shepherd Dog is so intent on their mission—whatever that may be— that they are virtually unsurpassed in working versatility. They are utterly devoted and faithful.
      They may be aloof and suspicious toward strangers, and protective of their home and family. They can be domineering. They can be assertive toward other dogs, but they are usually good with other pets.`,
    upkeep: `To care for a German Shepherd, you must feed him a highly nutritious diet, exercise him daily for 1.5 to 2 hours, and socialize him so that he feels safe around humans and other dogs. Ongoing training, twice-weekly grooming, and vet check-ups are all part of caring for a GSD.`,
    health: [
      `Major concerns: CHD`,
      `Minor concerns: Panosteitis, vWD`,
      `Suggested tests: hip, elbow (DNA for myelopathy)`,
      `Life span: 9 – 13 years`,
    ],
    size: 4,
    energyLvl: 3,
    exReqs: 4,
    playfulness: 2,
    affLvl: 3,
    frToDogs: 1,
    frToPets: 3,
    frToStr: 2,
    watchfulness: 5,
    easeTr: 5,
    groomReqs: 3,
    heatSens: 3,
    vocality: 5,
  },
  {
    name: `dachshund`,
    id: `dachshund`,
    cardDesc: `A short-legged, long-bodied, hound-type dog breed`,
    cardImg:
      "https://i.pinimg.com/564x/ac/3e/b4/ac3eb4fb2381bbffe3a4c4adad5f46ec.jpg",
    headImg:
      "https://www.macmillandictionary.com/external/slideshow/thumb/dachshund_thumb.jpg",
    subDesc: `(Also known as: the wiener dog, badger dog, and sausage dog)`,
    desc: `The Dachshund has an energetic, pleasant expression. Each of the three coat varieties has special attributes: the smooth is short and shining, imparting some protection against the elements; the long hair is sleek, sometimes slightly wavy, providing somewhat more protection; the wire has tight, thick, and hard hair with a finer undercoat, providing maximal protection.`,
    history: `Definitive evidence of the Dachshund as a breed isn’t found until the sixteenth century, when reference was made to a “low crooked legged” dog called a Little Burrow Dog, Dacksel, or Badger Dog. The modern name “Dachshund” means simply badger (dachs) dog (hund) in German.
      The Dachshund comes in three coat varieties and two sizes. The original Dachshunds were smooth coated and arose from crosses of the Bracke, a miniature French pointer, with the Pinscher. Some evidence exists of longer-haired Dachshund-like dogs in sixteenth-century woodcuts. It is also possible that smooth Dachshunds were later crossed with spaniels and the German Stoberhund (a gundog) to produce the long-haired variety. Mention is made of wire-coated Dachshunds as early as 1797, but these dogs were not carefully bred and most modern wires were created around the end of the nineteenth century by crossing smooth Dachshunds with German Wire-haired Pinschers and the Dandie Dinmont Terrier.
      Each of these varieties was best suited for hunting under slightly different terrain and climatic conditions, but all were tough, strong dogs capable of dispatching badger, fox, and other small mammals. Before 1900, very small Dachshunds were kept for going to ground after small quarry, such as rabbits. Although some were simply runts, others were intentionally produced by crosses with toy terriers or pinschers. Most of the resulting miniatures lacked Dachshund type, however.
      By 1910, stricter criteria were adopted for type, and each coat type was crossed with different breeds to achieve the best results: smooths were bred with the Miniature Pinscher, longs with the Papillon, and wires with the Miniature Schnauzer. The Dachshund has since found its real niche as a family pet, steadily rising in popularity to hold a place as one of the most popular hounds in America.`,
    temperament: `The Dachshund is bold, curious, and always up for adventure. He likes to explore and dig, tracking by scent. He is independent but will join in his family’s activities whenever given a chance. He is good with children in his own family, but some may snap at strange children. Most are reserved with strangers. Some bark. The longhaired variety may be quieter and less terrier-like; the wires may be more outgoing. Some miniatures are more prone to be timid.`,
    upkeep: `Although active, the Dachshund’s exercise requirements can be met with moderate walks on leash and games in the yard. He is amenable to city life or apartment living, but it is still a hunter by history and enjoys supervised forays into the field. The smooth coat requires minimal grooming. The long coat requires brushing or combing once or twice weekly and occasional trimming of stray hairs. The wire coat requires brushing or combing about once a week, with occasional trimming of stray hairs and professional grooming to remove dead hair twice a year.`,
    health: [
      `Major concerns: intervertebral disk disease`,
      `Minor concerns: KCS`,
      `Occasionally seen: diabetes, seizures, patellar luxation, gastric torsion, Cushing’s, deafness (in double dapples)`,
      `Suggested tests: eye, knee`,
      `Life span: 12–14 years`,
      `Note: Obesity is a common problem. “Double dapples” (homozygous merles) are more likely to have visual and hearing problems.`,
    ],
    size: 2,
    energyLvl: 4,
    exReqs: 2,
    playfulness: 3,
    affLvl: 3,
    frToDogs: 3,
    frToPets: 2,
    frToStr: 1,
    watchfulness: 2,
    easeTr: 2,
    groomReqs: 2,
    heatSens: 3,
    vocality: 5,
  },
  {
    name: `borzoi`,
    id: `borzoi`,
    cardDesc: `A Russian breed of hunting dog of sighthound type.`,
    cardImg:
      "https://i.pinimg.com/564x/08/ed/e8/08ede8ad8c63a931b1470394bad80e3b.jpg",
    headImg:
      "https://i.pinimg.com/originals/2f/aa/d9/2faad91c121e609735fa7a039c2a3dba.jpg",
    subDesc: `(Also known as Russian Hunting Sighthound)`,
    desc: `The Borzoi is a hound capable of running in a very cold climate, and has strong jaws. This breed retains the greyhound build necessary for running at great speed, but is larger and stronger than the greyhound. The long, silky coat, which can be either flat, wavy, or rather curly, provides protection against cold weather and snow. The Borzoi should possess elegance and grace, with flowing lines, whether standing or moving.`,
    history: `The Borzoi (also known as the Russian Wolf-hound) was bred by the Russian aristocracy for hundreds of years. Coursing for sport was known in Russia as early as the thirteenth century. In the fifteenth and sixteenth centuries, crosses of coursing hounds with bearhounds and with tall Russian sheepdogs were made to increase size and coat, both necessary for hunting in the cold climate
      The first standard was written in the 1600s in a book of Borzoi hunting rules. Perhaps no other breed has ever been the focus of hunting on such a grand scale. Hundreds of serfs worked in the upkeep of the hounds on huge estates; the hunts themselves were grand events. One account describes the hounds, horses, and hunters arriving in a train of over 40 cars, with another train bringing the Grand Duke and other nobility. Over 100 Borzoi might partake in a hunt.
      By the 1800s, seven distinct subtypes of Borzoi existed in Russia. Most present Borzoi descend from the Perchino type kept by the Grand Duke Nicolai Nicolayevitch, and many of the early American imports came directly from the Perchino kennels. The Russian Czar would often present Borzoi as gifts to visiting royalty.
      After the Russian Revolution, the days of the nobility were over, and the breed began to disappear. The fate of the breed was left in the hands of foreign royalty who had been given Borzoi and of a few remaining Borzoi kennels. In America, the Borzoi soon gained the reputation as the ultimate glamour dog, often seen at the sides of movie stars. Although only enjoying modest popularity as a pet, the breed remains popularity as a model.`,
    temperament: `A breed of quiet elegance, the Borzoi exemplifies the well-mannered family member indoors. Outdoors, they race with wild abandon, and will chase any small animal that runs. They are independent but very sensitive. Although generally good with children, they may not be playful enough to satisfy some children. Some can be timid. They are reserved with strangers.`,
    upkeep: `The Borzoi needs the chance for daily exertion. Although a long walk can satisfy most of their needs, it should be combined with a sprint in a large safe area. The coat, which is characteristically fuller on males, needs brushing or combing two or three times a week; at times it sheds a lot.`,
    health: [
      `Major concerns: gastric torsion`,
      `Minor concerns: cardiomyopathy, hypothyroidism`,
      `Occasionally seen: degenerative myelopathy (DM)`,
      `Suggested tests: thyroid, cardiac, DM`,
      `Life span: 10–12 years`,
      `Note: sensitive to barbiturate anesthesia`,
    ],
    size: 5,
    energyLvl: 2,
    exReqs: 3,
    playfulness: 3,
    affLvl: 3,
    frToDogs: 2,
    frToPets: 3,
    frToStr: 2,
    watchfulness: 3,
    easeTr: 2,
    groomReqs: 3,
    heatSens: 4,
    vocality: 2,
  },
  {
    name: `airedale`,
    id: `airedale`,
    cardDesc: `A breed of the terrier type from England`,
    cardImg:
      "https://i.pinimg.com/564x/30/b4/ef/30b4ef4381ec4bf008687cdfa4c6e614.jpg",
    headImg:
      "https://www.hundeo.com/wp-content/uploads/2019/01/Airedale-Terrier-1.jpg",
    subDesc: `(Also known as: Bingley Terrier and Waterside Terrier)`,
    desc: `The Airedale Terrier is a neat, upstanding, long-legged terrier, not exaggerated in any way. This breed has strong round bone and combines strength and agility. The Airedale has strong jaws and a free gait. The coat is hard, dense, and wiry; it lies straight and close, with some hair crinkling or waving.`,
    history: `Known as the King of Terriers, the Airedale is the tallest terrier. Like many terriers, this breed counts the old English, or Black and Tan, Terrier as one of its primary progenitors. These medium-sized dogs were prized by Yorkshire hunters (and poachers) for hunting a variety of game from water rat to fox. The dogs could also find and retrieve birds. Around the mid 1800s, some of these terriers around the River Aire in South Yorkshire were crossed with Otterhounds in order to improve their hunting ability around water, as well as their scenting ability. The result was a dog adept at otter hunting, originally called the Bingley or Waterside Terrier but recognized as the Airedale Terrier in 1878. Crosses to the Irish and Bull Terriers were made in order to reduce some of the remnants of the Otterhound cross that were now considered less than beautiful. By 1900, the patriarch of the breed, Champion Master Briar, was gaining renown, and his offspring carried on his influence in America. The Airedale’s size and gameness continued to win worldwide fame. This dog’s smart looks and manners won it a place as a police dog and family pet, both roles it still enjoys. After World War I, however, The Airedale’s popularity declined, and today this dog’s reputation is greater than its numbers.`,
    temperament: `Among the most versatile of terriers, the Airedale is bold, playful, and adventurous and is a lively yet protective companion. This breed is intelligent, but often stubborn and headstrong. Some can be domineering, but most are biddable, reliable, and responsive to their family’s wishes. Airedales make good family pets as long as they get daily mental and physical exercise. They like to be the head dog and may not do well when another dog challenges that position, although usually get along well with smaller dogs.`,
    upkeep: `This is an active breed that needs a chance to get vigorous exercise every day. The Airedale’s needs can be met with a long walk, a strenuous game, or a chance to hunt and romp in a safe area. The wire coat needs combing twice weekly, plus professional grooming every one to two months to layer the texture and color.`,
    health: [
      `Major concerns: CHD`,
      `Minor concerns: gastric torsion, hypothyroidism`,
      `Occasionally seen: colonic disease`,
      `Suggested tests: hip, thyroid`,
      `Life span: 10–13 years`,
    ],
    size: 3,
    energyLvl: 4,
    exReqs: 3,
    playfulness: 4,
    affLvl: 3,
    frToDogs: 1,
    frToPets: 2,
    frToStr: 4,
    watchfulness: 3,
    easeTr: 4,
    groomReqs: 3,
    heatSens: 4,
    vocality: 3,
  },
  {
    name: `doberman`,
    id: `doberman`,
    cardDesc: `A medium-large breed from Germany.`,
    cardImg:
      "https://i.pinimg.com/564x/76/5f/9c/765f9c2525c805b9de1e181bb57ff4e3.jpg",
    headImg:
      "https://media-be.chewy.com/wp-content/uploads/2021/06/02102805/Doberman-Pinscher_Featured-Image-1024x615.jpg",
    subDesc: `(Also known as Doberman Pinscher in the United States and Canada)`,
    desc: `The Doberman is compactly built, muscular and powerful. They combine elegance and strength, speed and endurance. Their carriage is proud and alert, and their gait is free and vigorous. The Doberman coat is short, smooth, and hard, showing off the exceptionally clean-cut lines of this athletic breed.`,
    history: `Few people can claim to have had so great an impact upon the dog world as Louis Dobermann of Thuringen, Germany. Herr Doberman was a door-to-door tax collector who needed a dog to accompany him on his rounds. In the late 1800s he set about to create an alert streamlined guard dog, most likely by crossing the old German Shepherd and German Pinscher, with later crosses to the Black and Tan Manchester Terrier, Greyhound, and Weimaraner. He soon obtained the prototype of the breed that now bears his name.
      The original Dobermans were still somewhat heavy boned and roundheaded; subsequent breeders selected for a more racy-looking dog. The breed evolved in remarkable time; by 1899 the first breed club was formed. The breed continued to attract acclaim, and the first Doberman arrived in America in 1908. They soon found favor throughout Europe and America as a police dog, and later as a war dog. Their prowess in these areas soon brought more admirers, and the Doberman quickly became a valued family pet. Their chiseled silhouette and fearless alert demeanor has made the Doberman a top contender as a show dog.
      As their fame grew, many families grew to appreciate the breed as a family pet, and the Doberman eventually rose to be the second most popular breed in America in 1977. Unfortunately, the media cast the Dobe in the role of a vicious breed and their reputation unfairly suffered. During this same time period, albinistic white Dobermans emerged. In an effort to decrease the chance of producing these dogs, the Doberman Pinscher Club of America convinced the AKC to tag the registration numbers of dogs with the likelihood of carrying the albino gene with the letter Z (a DNA test is now available).`,
    temperament: `The Doberman Pinscher is an intelligent capable guardian, ever on the alert and ready to protect its family or home. He is also a loyal and adventurous companion. He likes to be mentally challenged, and is a gifted obedience, agility, and Schutzhund pupil. He is sensitive, and very responsive to his owner’s wishes, though some can be domineering. He is generally reserved with strangers. It can be assertive with strange dogs.`,
    upkeep: `This is an active breed that needs daily mental and physical exercise lest they become frustrated or destructive. Their exercise requirements can be met with a long jog or walk on leash, or a strenuous run in a safe area. Coat care is minimal.`,
    health: [
      `Major concerns: CVI (wobbler’s syndrome), cardiomyopathy`,
      `Minor concerns: vWD, demodicosis, osteosarcoma, gastric torsion, CHD`,
      `Occasionally seen: albinism, hypothyroidism, PRA, narcolepsy`,
      `Suggested tests: cardiac (Holter monitor), hip, eye, DNA for vWD, thyroid`,
      `Life span: 10–12 years`,
      `Note: Blue Dobermans sometimes have hair loss; “white” Dobermans are albinos and are light-sensitive`,
    ],
    size: 4,
    energyLvl: 4,
    exReqs: 3,
    playfulness: 3,
    affLvl: 3,
    frToDogs: 2,
    frToPets: 3,
    frToStr: 1,
    watchfulness: 5,
    easeTr: 5,
    groomReqs: 1,
    heatSens: 3,
    vocality: 5,
  },
  {
    name: `pug`,
    id: `pug`,
    cardDesc: `A Chinese breed with physically distinctive features`,
    cardImg:
      "https://i.pinimg.com/564x/f6/56/13/f65613d6ae285312dc71c87207bc33df.jpg",
    headImg: "https://cdn.britannica.com/34/233234-050-1649BFA9/Pug-dog.jpg",
    subDesc: `(Also known as: Mops, Carlin)`,
    desc: `Square-proportioned, compact and of a stocky build, the Pug is a large dog in a little space. Their gait is strong and jaunty, but with a slight roll of the hindquarters. Their distinctive expression is soft and solicitous. Their forehead has large, deep wrinkles. Their coat is fine, smooth, and short.`,
    history: `The Pug has been known by many names: Mopshond in Holland (which refers to its grumbling tendencies); Mops in Germany, and Dutch or Chinese Pug in England. The word Pug is derived either from the Latin pugnus meaning fist, as the head may have resembled a clenched fist, or from the marmoset “Pug” monkeys that the Pug dogs somewhat resemble.
      Whatever the name, one thing is true: the Pug’s official motto “Multum in Parvo” (a lot in a little) fits them exactly. The Pug is somewhat of an exception in the Toy Group because they are perhaps the only one to be descended from mastiff forebears. Although their exact ancestry has been lost in antiquity, the Pug retains many mastiff characteristics.
      The Pug is an ancient breed, one of several miniaturized in the Orient, where they were a favorite pet of Buddhist monasteries in Tibet many centuries ago. In China, the facial wrinkles were an essential breed feature, most notably the “prince mark,” or vertical wrinkle on their forehead, which bore a resemblance to the Chinese character for “prince.”
      Pugs probably came to Holland by way of the Dutch East India Trading Company. Here they became quite popular and were recognized as the official dog of the House of Orange after one saved the life of Prince William by sounding an alarm at the approach of Spanish soldiers in 1572.
      By 1790, the Pug could be found in France; Napoleon’s wife Josephine used her Pug to carry messages to Napoleon when she was imprisoned. Pugs were first brought to England during Victorian times and became incredibly popular with the wealthy, displacing the King Charles Spaniel as the favored royal breed. Several Pugs were brought to England from China in 1886. A year earlier, the breed had been recognized by the AKC. Since that time, they have remained popular a pet.`,
    temperament: `A delightful blend of dignity and comedy, the Pug is an amiable, playful, and confident companion. They can be stubborn and headstrong, but they are pleasant and generally willing to please. They love to cavort and show off.`,
    upkeep: `The Pug needs daily exercise, either in the form of a lively game or a moderate walk. They do not do well in heat and humidity. They needs minimal coat care but daily cleaning of facial wrinkles. Their smooth coat needs only occasional brushing to remove dead hairs; however, the wrinkles need regular cleaning and drying to prevent skin infections. The Pug may often wheeze and snore.`,
    health: [
      `Major concerns: Pug dog encephalitis, CHD, brachycephalic syndrome`,
      `Minor concerns: elongated palate, stenotic nares, patellar luxation, Legg-Perthes, entropion, KCS, skin infections, hemivertebra`,
      `Occasionally seen: seizures, nerve degeneration, distichiasis, allergies, demodicosis`,
      `Suggested tests: eye, hip, knee, DNA Pug dog encephalitis`,
      `Life span: 12–15 years`,
      `Note: The Pug cannot tolerate heat and is sensitive to anesthesia. They are prone to corneal abrasion and obesity.`,
    ],
    size: 1,
    energyLvl: 3,
    exReqs: 2,
    playfulness: 4,
    affLvl: 4,
    frToDogs: 3,
    frToPets: 3,
    frToStr: 2,
    watchfulness: 1,
    easeTr: 3,
    groomReqs: 2,
    heatSens: 5,
    vocality: 5,
  },
  {
    name: `shar pei`,
    id: `sharpei`,
    cardDesc: `A dog breed from southern China.`,
    cardImg:
      "https://i.pinimg.com/564x/06/7f/28/067f28c9620a8a0fff3d0b7a9410a637.jpg",
    headImg:
      "https://img.freepik.com/premium-photo/house-dog-SharPei-red-color-looks-away_610315-5067.jpg?w=2000",
    subDesc: `(Chinese Shar Pei)`,
    desc: `The Shar Pei is compact and square, with a head slightly large for their body. The coat can be of either brush (not to exceed 1 inch) or horse (very short) types, both it should be extremely harsh, straight, and stand off the body. The gait is free, with good reach and drive. The wide jaws, scowling expression, and hippopotamus muzzle create a look unique to the breed.`,
    history: `The Chinese Shar Pei may have existed in the southern provinces of China since the Han dynasty (around 200 b.c.). Certainly by the thirteenth century strong evidence in the form of writings describing a wrinkled dog point to the breed’s existence. Its origins are unknown, but because only it and the Chow Chow have blue-black tongues, and both come from China, it is likely that they share some common ancestry. The Shar-Pei’s history is difficult to trace because most records relating to its past were lost when China became communist. At this time Shar-Peis were the working breed of peasant farmers, fulfilling roles of guard dog and wild boar hunter.
      After the nation became communist, most of China’s dogs were eliminated, with only a few remaining outside of the cities. A few Shar-Peis were bred in British Hong Kong and Taiwan, and the Hong Kong Kennel Club recognized the breed in 1968. Around this same time, a few specimens came to America, but the turning point occurred with a 1973 article alerting American fanciers to the breed’s perilously low numbers. Touted as the world’s rarest dog, fanciers vied to obtain the few available Shar-Peis. The breed has since been brought from the brink of extinction to the height of popularity, and it is one of the most recognizable breeds in America. Though known for its loose skin and profuse wrinkles, which are superabundant in puppies, the wrinkles of adults may be limited only to the head, neck, and shoulders.`,
    temperament: `The Shar Pei can be self-assured, serious, independent, stubborn, and very much self-possessed. Although not particularly demonstrative, he is devoted and may be very protective of his family. He is reserved, even suspicious, toward strangers. He can be assertive toward other dogs and may chase livestock and other animals, although he is generally good with other family pets.`,
    upkeep: `The Shar Pei needs daily mental and physical stimulation, but his needs can be met with lively games throughout the day or a good long walk. The coat needs only weekly brushing, but wrinkles need regular attention to ensure that no irritations develop within the skin folds. The name Shar Pei means sandy coat, referring to the gritty sandpaper texture of the coat. When rubbed backward, the prickly coat can be uncomfortable, and even cause welts on the skin of an occasional sensitive person.`,
    health: [
      `Major concerns: entropion, CHD`,
      `Minor concerns: patellar luxation, allergies, otitis externa, lip and skin fold pyodermas, hypothyroidism, amyloidosis (renal)`,
      `Occasionally seen: megaesophagus`,
      `Suggested tests: hip, knee, elbow, eye, thyroid`,
      `Life span: 8–10 years`,
      `Note: Some dogs get Shar Pei fever, a periodic inflammatory response caused, as a result of the mutation, causing skin wrinkling.`,
    ],
    size: 3,
    energyLvl: 3,
    exReqs: 3,
    playfulness: 1,
    affLvl: 1,
    frToDogs: 1,
    frToPets: 3,
    frToStr: 1,
    watchfulness: 4,
    easeTr: 1,
    groomReqs: 2,
    heatSens: 4,
    vocality: 5,
  },
];

export default breedInfoData;
